name = 'Default'
bgcol = '00FF00'
filtermode = 'nearest'

[[emotions]]
talkmode = 'jump:64:1024'
idlesize = '512x512'
speaksize = '512x512'

[[emotions]]
talkmode = 'shake:256'
idlesize = '512x512'
speaksize = '512x512'